// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: ristcached/v1/ristcached.proto

package ristcachedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Cost  int64  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Ttl   int64  `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *KeyValue) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found bool   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *KeyValue `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{3}
}

func (x *SetRequest) GetItem() *KeyValue {
	if x != nil {
		return x.Item
	}
	return nil
}

type SetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Added bool `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{4}
}

func (x *SetResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type SetWithTTLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *KeyValue `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *SetWithTTLRequest) Reset() {
	*x = SetWithTTLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWithTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWithTTLRequest) ProtoMessage() {}

func (x *SetWithTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWithTTLRequest.ProtoReflect.Descriptor instead.
func (*SetWithTTLRequest) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{5}
}

func (x *SetWithTTLRequest) GetItem() *KeyValue {
	if x != nil {
		return x.Item
	}
	return nil
}

type SetWithTTLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Added bool `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
}

func (x *SetWithTTLResponse) Reset() {
	*x = SetWithTTLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetWithTTLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWithTTLResponse) ProtoMessage() {}

func (x *SetWithTTLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWithTTLResponse.ProtoReflect.Descriptor instead.
func (*SetWithTTLResponse) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{6}
}

func (x *SetWithTTLResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type DelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{7}
}

func (x *DelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{8}
}

type GetTTLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetTTLRequest) Reset() {
	*x = GetTTLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTTLRequest) ProtoMessage() {}

func (x *GetTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTTLRequest.ProtoReflect.Descriptor instead.
func (*GetTTLRequest) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{9}
}

func (x *GetTTLRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetTTLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ttl   int64 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Found bool  `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *GetTTLResponse) Reset() {
	*x = GetTTLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTTLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTTLResponse) ProtoMessage() {}

func (x *GetTTLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTTLResponse.ProtoReflect.Descriptor instead.
func (*GetTTLResponse) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{10}
}

func (x *GetTTLResponse) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *GetTTLResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type UpdateMaxCostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxCost int64 `protobuf:"varint,1,opt,name=max_cost,json=maxCost,proto3" json:"max_cost,omitempty"`
}

func (x *UpdateMaxCostRequest) Reset() {
	*x = UpdateMaxCostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMaxCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMaxCostRequest) ProtoMessage() {}

func (x *UpdateMaxCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMaxCostRequest.ProtoReflect.Descriptor instead.
func (*UpdateMaxCostRequest) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMaxCostRequest) GetMaxCost() int64 {
	if x != nil {
		return x.MaxCost
	}
	return 0
}

type UpdateMaxCostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateMaxCostResponse) Reset() {
	*x = UpdateMaxCostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMaxCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMaxCostResponse) ProtoMessage() {}

func (x *UpdateMaxCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMaxCostResponse.ProtoReflect.Descriptor instead.
func (*UpdateMaxCostResponse) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{12}
}

type MaxCostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MaxCostRequest) Reset() {
	*x = MaxCostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxCostRequest) ProtoMessage() {}

func (x *MaxCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxCostRequest.ProtoReflect.Descriptor instead.
func (*MaxCostRequest) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{13}
}

type MaxCostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxCost int64 `protobuf:"varint,1,opt,name=max_cost,json=maxCost,proto3" json:"max_cost,omitempty"`
}

func (x *MaxCostResponse) Reset() {
	*x = MaxCostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxCostResponse) ProtoMessage() {}

func (x *MaxCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxCostResponse.ProtoReflect.Descriptor instead.
func (*MaxCostResponse) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{14}
}

func (x *MaxCostResponse) GetMaxCost() int64 {
	if x != nil {
		return x.MaxCost
	}
	return 0
}

type ClearRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{15}
}

type ClearResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearResponse) Reset() {
	*x = ClearResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResponse) ProtoMessage() {}

func (x *ClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResponse.ProtoReflect.Descriptor instead.
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{16}
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{17}
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CostAdded    uint64  `protobuf:"varint,1,opt,name=cost_added,json=costAdded,proto3" json:"cost_added,omitempty"`
	CostEvicted  uint64  `protobuf:"varint,2,opt,name=cost_evicted,json=costEvicted,proto3" json:"cost_evicted,omitempty"`
	GetsDropped  uint64  `protobuf:"varint,3,opt,name=gets_dropped,json=getsDropped,proto3" json:"gets_dropped,omitempty"`
	GetsKept     uint64  `protobuf:"varint,4,opt,name=gets_kept,json=getsKept,proto3" json:"gets_kept,omitempty"`
	Hits         uint64  `protobuf:"varint,5,opt,name=hits,proto3" json:"hits,omitempty"`
	KeysAdded    uint64  `protobuf:"varint,6,opt,name=keys_added,json=keysAdded,proto3" json:"keys_added,omitempty"`
	KeysEvicted  uint64  `protobuf:"varint,7,opt,name=keys_evicted,json=keysEvicted,proto3" json:"keys_evicted,omitempty"`
	KeysUpdated  uint64  `protobuf:"varint,8,opt,name=keys_updated,json=keysUpdated,proto3" json:"keys_updated,omitempty"`
	Misses       uint64  `protobuf:"varint,9,opt,name=misses,proto3" json:"misses,omitempty"`
	Ratio        float32 `protobuf:"fixed32,10,opt,name=ratio,proto3" json:"ratio,omitempty"`
	SetsDropped  uint64  `protobuf:"varint,11,opt,name=sets_dropped,json=setsDropped,proto3" json:"sets_dropped,omitempty"`
	SetsRejected uint64  `protobuf:"varint,12,opt,name=sets_rejected,json=setsRejected,proto3" json:"sets_rejected,omitempty"`
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ristcached_v1_ristcached_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ristcached_v1_ristcached_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_ristcached_v1_ristcached_proto_rawDescGZIP(), []int{18}
}

func (x *GetMetricsResponse) GetCostAdded() uint64 {
	if x != nil {
		return x.CostAdded
	}
	return 0
}

func (x *GetMetricsResponse) GetCostEvicted() uint64 {
	if x != nil {
		return x.CostEvicted
	}
	return 0
}

func (x *GetMetricsResponse) GetGetsDropped() uint64 {
	if x != nil {
		return x.GetsDropped
	}
	return 0
}

func (x *GetMetricsResponse) GetGetsKept() uint64 {
	if x != nil {
		return x.GetsKept
	}
	return 0
}

func (x *GetMetricsResponse) GetHits() uint64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *GetMetricsResponse) GetKeysAdded() uint64 {
	if x != nil {
		return x.KeysAdded
	}
	return 0
}

func (x *GetMetricsResponse) GetKeysEvicted() uint64 {
	if x != nil {
		return x.KeysEvicted
	}
	return 0
}

func (x *GetMetricsResponse) GetKeysUpdated() uint64 {
	if x != nil {
		return x.KeysUpdated
	}
	return 0
}

func (x *GetMetricsResponse) GetMisses() uint64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *GetMetricsResponse) GetRatio() float32 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *GetMetricsResponse) GetSetsDropped() uint64 {
	if x != nil {
		return x.SetsDropped
	}
	return 0
}

func (x *GetMetricsResponse) GetSetsRejected() uint64 {
	if x != nil {
		return x.SetsRejected
	}
	return 0
}

var File_ristcached_v1_ristcached_proto protoreflect.FileDescriptor

var file_ristcached_v1_ristcached_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2f, 0x76, 0x31, 0x2f,
	0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x22,
	0x58, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x22, 0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x39, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x22, 0x39, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22,
	0x23, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61,
	0x64, 0x64, 0x65, 0x64, 0x22, 0x40, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x54,
	0x54, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x2a, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x64, 0x64,
	0x65, 0x64, 0x22, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x0d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x21, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x38, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x54, 0x4c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x31,
	0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x78, 0x43, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x73,
	0x74, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x78, 0x43, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x4d, 0x61,
	0x78, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2c, 0x0a, 0x0f,
	0x4d, 0x61, 0x78, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x85, 0x03, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x73, 0x74, 0x5f,
	0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x6f, 0x73,
	0x74, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x65,
	0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x6f,
	0x73, 0x74, 0x45, 0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x65, 0x74,
	0x73, 0x5f, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x67, 0x65, 0x74, 0x73, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x67, 0x65, 0x74, 0x73, 0x5f, 0x6b, 0x65, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x67, 0x65, 0x74, 0x73, 0x4b, 0x65, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x74,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x68, 0x69, 0x74, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x6b, 0x65, 0x79, 0x73, 0x5f, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x73, 0x41, 0x64, 0x64, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x6b, 0x65, 0x79, 0x73, 0x5f, 0x65, 0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x6b, 0x65, 0x79, 0x73, 0x45, 0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x6b, 0x65, 0x79, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6b, 0x65, 0x79, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x74, 0x73, 0x5f, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x73, 0x65, 0x74, 0x73, 0x44, 0x72, 0x6f, 0x70,
	0x70, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x74, 0x73, 0x5f, 0x72, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x65, 0x74, 0x73,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x32, 0xb6, 0x05, 0x0a, 0x11, 0x52, 0x69, 0x73,
	0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e,
	0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e,
	0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53,
	0x0a, 0x0a, 0x53, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x54, 0x54, 0x4c, 0x12, 0x20, 0x2e, 0x72,
	0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74,
	0x57, 0x69, 0x74, 0x68, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x19, 0x2e, 0x72, 0x69, 0x73,
	0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x54, 0x54, 0x4c, 0x12, 0x1c, 0x2e,
	0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x69,
	0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x54, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x07,
	0x4d, 0x61, 0x78, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x78, 0x43, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x78, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x78, 0x43, 0x6f, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x72, 0x69, 0x73, 0x74,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x78, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x78, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x05, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x12,
	0x1b, 0x2e, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72,
	0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x65,
	0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x20, 0x2e, 0x72, 0x69, 0x73,
	0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x72,
	0x69, 0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x61, 0x63, 0x68, 0x75, 0x6e, 0x77, 0x75, 0x2f, 0x72, 0x69, 0x73, 0x74, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x69,
	0x73, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x69, 0x73, 0x74,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ristcached_v1_ristcached_proto_rawDescOnce sync.Once
	file_ristcached_v1_ristcached_proto_rawDescData = file_ristcached_v1_ristcached_proto_rawDesc
)

func file_ristcached_v1_ristcached_proto_rawDescGZIP() []byte {
	file_ristcached_v1_ristcached_proto_rawDescOnce.Do(func() {
		file_ristcached_v1_ristcached_proto_rawDescData = protoimpl.X.CompressGZIP(file_ristcached_v1_ristcached_proto_rawDescData)
	})
	return file_ristcached_v1_ristcached_proto_rawDescData
}

var file_ristcached_v1_ristcached_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_ristcached_v1_ristcached_proto_goTypes = []interface{}{
	(*KeyValue)(nil),              // 0: ristcached.v1.KeyValue
	(*GetRequest)(nil),            // 1: ristcached.v1.GetRequest
	(*GetResponse)(nil),           // 2: ristcached.v1.GetResponse
	(*SetRequest)(nil),            // 3: ristcached.v1.SetRequest
	(*SetResponse)(nil),           // 4: ristcached.v1.SetResponse
	(*SetWithTTLRequest)(nil),     // 5: ristcached.v1.SetWithTTLRequest
	(*SetWithTTLResponse)(nil),    // 6: ristcached.v1.SetWithTTLResponse
	(*DelRequest)(nil),            // 7: ristcached.v1.DelRequest
	(*DelResponse)(nil),           // 8: ristcached.v1.DelResponse
	(*GetTTLRequest)(nil),         // 9: ristcached.v1.GetTTLRequest
	(*GetTTLResponse)(nil),        // 10: ristcached.v1.GetTTLResponse
	(*UpdateMaxCostRequest)(nil),  // 11: ristcached.v1.UpdateMaxCostRequest
	(*UpdateMaxCostResponse)(nil), // 12: ristcached.v1.UpdateMaxCostResponse
	(*MaxCostRequest)(nil),        // 13: ristcached.v1.MaxCostRequest
	(*MaxCostResponse)(nil),       // 14: ristcached.v1.MaxCostResponse
	(*ClearRequest)(nil),          // 15: ristcached.v1.ClearRequest
	(*ClearResponse)(nil),         // 16: ristcached.v1.ClearResponse
	(*GetMetricsRequest)(nil),     // 17: ristcached.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),    // 18: ristcached.v1.GetMetricsResponse
}
var file_ristcached_v1_ristcached_proto_depIdxs = []int32{
	0,  // 0: ristcached.v1.SetRequest.item:type_name -> ristcached.v1.KeyValue
	0,  // 1: ristcached.v1.SetWithTTLRequest.item:type_name -> ristcached.v1.KeyValue
	1,  // 2: ristcached.v1.RistcachedService.Get:input_type -> ristcached.v1.GetRequest
	3,  // 3: ristcached.v1.RistcachedService.Set:input_type -> ristcached.v1.SetRequest
	5,  // 4: ristcached.v1.RistcachedService.SetWithTTL:input_type -> ristcached.v1.SetWithTTLRequest
	7,  // 5: ristcached.v1.RistcachedService.Del:input_type -> ristcached.v1.DelRequest
	9,  // 6: ristcached.v1.RistcachedService.GetTTL:input_type -> ristcached.v1.GetTTLRequest
	13, // 7: ristcached.v1.RistcachedService.MaxCost:input_type -> ristcached.v1.MaxCostRequest
	11, // 8: ristcached.v1.RistcachedService.UpdateMaxCost:input_type -> ristcached.v1.UpdateMaxCostRequest
	15, // 9: ristcached.v1.RistcachedService.Clear:input_type -> ristcached.v1.ClearRequest
	17, // 10: ristcached.v1.RistcachedService.GetMetrics:input_type -> ristcached.v1.GetMetricsRequest
	2,  // 11: ristcached.v1.RistcachedService.Get:output_type -> ristcached.v1.GetResponse
	4,  // 12: ristcached.v1.RistcachedService.Set:output_type -> ristcached.v1.SetResponse
	6,  // 13: ristcached.v1.RistcachedService.SetWithTTL:output_type -> ristcached.v1.SetWithTTLResponse
	8,  // 14: ristcached.v1.RistcachedService.Del:output_type -> ristcached.v1.DelResponse
	10, // 15: ristcached.v1.RistcachedService.GetTTL:output_type -> ristcached.v1.GetTTLResponse
	14, // 16: ristcached.v1.RistcachedService.MaxCost:output_type -> ristcached.v1.MaxCostResponse
	12, // 17: ristcached.v1.RistcachedService.UpdateMaxCost:output_type -> ristcached.v1.UpdateMaxCostResponse
	16, // 18: ristcached.v1.RistcachedService.Clear:output_type -> ristcached.v1.ClearResponse
	18, // 19: ristcached.v1.RistcachedService.GetMetrics:output_type -> ristcached.v1.GetMetricsResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_ristcached_v1_ristcached_proto_init() }
func file_ristcached_v1_ristcached_proto_init() {
	if File_ristcached_v1_ristcached_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ristcached_v1_ristcached_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetWithTTLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetWithTTLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTTLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTTLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMaxCostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMaxCostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxCostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxCostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ristcached_v1_ristcached_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ristcached_v1_ristcached_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ristcached_v1_ristcached_proto_goTypes,
		DependencyIndexes: file_ristcached_v1_ristcached_proto_depIdxs,
		MessageInfos:      file_ristcached_v1_ristcached_proto_msgTypes,
	}.Build()
	File_ristcached_v1_ristcached_proto = out.File
	file_ristcached_v1_ristcached_proto_rawDesc = nil
	file_ristcached_v1_ristcached_proto_goTypes = nil
	file_ristcached_v1_ristcached_proto_depIdxs = nil
}
